### ISSUE TITLE
[BUG] in check_vignette

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgstats#28]
@steffilazerte Your `weathercan` package is a very helpful example indeed! The vignettes checks reports 12, yet you only have 10, so something is awry there too. Ping @maelle, author of original vignette check.

**Comment by mpadge** [comment]
Aha, actually comes from the number extracted by `pkgstats`, which needs to be updated to reflect @maelle's superior code.

**Comment by mpadge** [comment]
@maelle Vignette counting has been updated here to reflect the same code in the vignette checks of `pkgcheck` (which also had to be updated, because of @steffitlazerte's [fine example with sub-directories in the vignettes dir](https://github.com/ropensci/weathercan/tree/master/vignettes)). The reported number is now the overall number of `.Rmd` files BUT this count does not do the `is_html` check. The main `pkgcheck` itself thus remains a confirmation that there is at least one HTML vignette, while the number here, and therefore in the extended `pkgcheck` output, is simply that regardless of `rmarkdown::default_output_format()`. Just so that we all understand here :smile:

**Comment by maelle** [comment]
Thanks for the clarification!

If I remember correctly my code came from pkgdown.

**Comment by mpadge** [comment]
@maelle Just another FYI here that this actually has to be reverted to previous version, because `pkgstats` must remain truly general and applicable to the entire history of R packages long before `.Rmd` was even a thing. I'll then modify downstream to ensure the numbers reported by `pkgcheck` are indeed correct.

**Comment by mpadge** [comment]
Actually even easier to just modify here - count `.Rmd` files if there are any, otherwise count `.R` files. That code doesn't apply to CRAN tarballs from the mirror anyway, so should be perfectly okay in that form.
