### ISSUE TITLE
Error: There is no package called <...>

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgstats#40]
From @maelle:

``` r
library (pkgstats)
package = list(identifier = "taxa", codeRepository = "https://github.com/ropensci/taxa")
temp_dir <- withr::local_tempdir()
repo <- remotes::parse_github_url(package[["codeRepository"]])
gert::git_clone(
    url = sprintf("https://github.com/%s/%s", repo[["username"]], repo[["repo"]]),
    path = temp_dir
)
stats <- pkgstats::pkgstats(temp_dir)
#> Error:  there is no package called 'taxa'
```

<sup>Created on 2022-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mpadge** [comment]
The :bug: and corresponding error message came from this call https://github.com/ropensci-review-tools/pkgstats/blob/ecb314e34c56d46b23b2b19e75cb914922f02f2d/R/rd-stats.R#L121 to [`tools::Rd2txt()`](https://stat.ethz.ch/R-manual/R-patched/library/tools/html/Rd2HTML.html). Reading through the details there, `taxa` obviously includes an `\Sexpr` macro in one man file, which is executed by default at "render" time, which follows "install". Those execution times are in turn defined by a `stages` parameter, so the solution is to just hard-code that as `stages = "build"`, which is the first possible stage.

**Comment by mpadge** [comment]
Further info: This happens because of stuff like [these lines in `taxa`](https://github.com/ropensci/taxa/blob/79b74d4a53256c740ff4603ff46ffdc8caa5980c/R/documentation.R#L41-L49), which are in turn taken directly from tidyverse code, and insert Sexpr macros with explicit `stages = "render"` arguments to insert lifecycle svg badges directly into man files. The solution above simply overrides this values of `stages` with "build", and so fails to render any (lifecycle or other) svgs in man files, but enables `tools::Rd2txt()` to work. So it's not a solution as much as just a tricky workaround.

**Comment by maelle** [comment]
Thanks for the digging & working-around!
