### ISSUE TITLE
Counts of external calls may be inaccurate

### ISSUE THREAD

**Issue by pawelru** [ropensci-review-tools/pkgstats#61]
I have found the calculation of external calls quite inaccurate.  Please find below a few examples. 

Reading the source code I am aware that it's probably an imperfection of external dependent `ctags`. It might do well other things (like accounting internal vars) but for counting dependent packages I have found it not detecting occurrences which results in undercounting totals or not including some at all.

It's difficult to ask you to _fix_ it and I'm just sharing my findings with you. Maybe you can consider alternative ways of getting what's needed? I'm aware of relatively new [`treesitter`](https://davisvaughan.github.io/r-tree-sitter/) but I personally have no experience in it. Maybe `checkglobals` show here?

Checking a randomly selected [`teal`](https://github.com/insightsengineering/teal) repo that I'm working on:
- `pkgstats` gives me this:
```
r$> x[, c("pkg", "n_unique")]
             pkg n_unique
1             R6        1
2           base       93
3      checkmate       21
4         future        2
5       graphics        2
6       jsonlite        1
7        methods        7
8       promises        2
9          rlang        4
10         rvest        1
11         shiny        6
12       shinyjs        2
13    shinytest2        1
14         stats        3
15          teal      101
16     teal.code        2
17     teal.data        4
18 teal.reporter        1
19    teal.slice        3
20  teal.widgets        1
21         utils        8
22          yaml        1
```

(where `x` is defined as per the [vignette](https://docs.ropensci.org/pkgstats/articles/pkgstats.html?q=external#external_calls-all-calls-made-to-all-r-functions))

- while `checkglobals` (I'm not an author) reports me this:
```
r$> as.data.frame(x) |> dplyr::group_by(package) |> dplyr::summarise(n_unique = dplyr::n()) |> print(n = Inf)
# A tibble: 27 × 2
   package       n_unique
   <chr>            <int>
 1 R6                   1
 2 checkmate           28
 3 future               3
 4 jsonlite             1
 5 lifecycle            2
 6 logger               1
 7 methods              5
 8 promises             2
 9 renv                 1
10 rlang                6
11 rvest                4
12 shiny               59
13 shinyjs              8
14 shinytest2           2
15 stats                2
16 teal                 2
17 teal.code            3
18 teal.data            5
19 teal.logger          3
20 teal.reporter        4
21 teal.slice           7
22 teal.widgets         3
23 testthat             4
24 tools                1
25 utils                3
26 yaml                 1
27 NA                   6
```

I'm aware of some differences, e.g. you include `R/` dir only while `checkglobals` look into all dirs (incl. tests, vignettes etc.) but nevertheless the latter seems to be more accurate to me. A few examples using imperfect regexp on my local clone just to show you why I think that the values are incorrect:

- `teal.reporter` dependency
    - `checkglobals` reports 4 unique
    - `pkgstats` reports 1 unique
    - GH search (includes also occurences in docs) - [link](https://github.com/search?q=repo%3Ainsightsengineering%2Fteal+teal.reporter%3A%3A+path%3A%2F%5ER%5C%2F%2F&type=code)
    - local search in `R/`
```
❯ grep -rP '^[^#].*teal.reporter::' R/
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
❯ grep -r '^[^#].*teal.reporter::' R/
R//teal_reporter.R:  inherit = teal.reporter::ReportCard,
R//teal_reporter.R:  inherit = teal.reporter:::TextBlock,
R//reporter_previewer_module.R:  checkmate::assert_true(all(names(server_args) %in% names(formals(teal.reporter::reporter_previewer_srv))))
R//reporter_previewer_module.R:    teal.reporter::reporter_previewer_srv(id, reporter, ...)
R//reporter_previewer_module.R:    teal.reporter::reporter_previewer_ui(id, ...)
R//modules.R:      "\n - `reporter` - module will receive `Reporter`. See `help(teal.reporter::Reporter)`",
R//init.R:  reporter <- teal.reporter::Reporter$new()$set_id(attr(filter, "app_id"))
R//module_nested_tabs.R:                            reporter = teal.reporter::Reporter$new(),
R//module_nested_tabs.R:                                    reporter = teal.reporter::Reporter$new(),
R//module_nested_tabs.R:                                         reporter = teal.reporter::Reporter$new(),
R//module_nested_tabs.R:                                        reporter = teal.reporter::Reporter$new(),
```
`pkgstats` reports just one unique occurence

- `renv`
    - `checkglobals` reports 1 unique
    - `pkgstats` reports 0
    - GH search (includes also occurences in docs) - [link](https://github.com/search?q=repo%3Ainsightsengineering%2Fteal+renv%3A%3A+path%3A%2F%5ER%5C%2F%2F&type=code)
    - local search in `R/`
```
❯ grep -r "^[^#].*renv::" R/

R//teal_lockfile.R:      renv::snapshot(
R//teal_lockfile.R:        # type = is taken from renv::settings$snapshot.type()
```

- `shinyjs`
    - `checkglobals` reports 8 unique
    - `pkgstats` reports 2 unique
    - GH search (includes also occurences in docs) - [link](https://github.com/search?q=repo%3Ainsightsengineering%2Fteal+shinyjs%3A%3A+path%3A%2F%5ER%5C%2F%2F&type=code)
    - local search in `R/`
```
❯ grep -r "^[^#].*shinyjs::" R/

R//utils.R:  shinyjs::runjs(script) # function does not return anything
R//include_css_js.R:    shinyjs::runjs(paste0(readLines(system.file("js", file, package = "teal", mustWork = TRUE)), collapse = "\n"))
R//include_css_js.R:    shinyjs::useShinyjs(),
R//include_css_js.R:    shinyjs::hidden(icon("fas fa-gear")), # add hidden icon to load font-awesome css for icons
R//module_snapshot_manager.R:        shinyjs::click(id = "teal-wunder_bar-show_snapshot_manager", asis = TRUE)
R//module_init_data.R:      shinyjs::showLog()
R//module_init_data.R:      shinyjs::disable(selector = sprintf(".teal-body:has('#%s') .nav li a", session$ns("content")))
R//module_init_data.R:      shinyjs::enable(selector = sprintf(".teal-body:has('#%s') .nav li a", session$ns("content")))
R//module_init_data.R:        shinyjs::hide(
R//module_init_data.R:        shinyjs::runjs(
```

**Comment by pawelru** [comment]
Thanks @mpadge for a prompt and very detailed response - I really appreciate that. Especially that you actually went beyond into the referenced codebase and explain individual examples. Very much appreciated.

Let me begin by saying that I never intended to offend anyone in my previous message. My aim was to simply share some feedback on things that I found concerning. I believe that the constructive feedback is essential, especially in the context of open-sourcing. By this, I mean reports, not criticism. I am sorry if my words were misunderstood. 

I totally agree with you that this is not a trivial problem. My background is that I am looking for a measures of a _dependency_ of a package. My first idea was to measure _the usage_ of the objects and I am currently experimenting with different tools. Your message makes me realise that this (`ctags`) is meant for something different - i.e. counting external function calls which in some cases makes a big difference - e.g. whether or not to include `foo::bar`. On that note, I think that `ctags` results are correct. As you explained in details. I was just looking for something different and unintentionally misunderstood the results.

**Comment by mpadge** [comment]
@pawelru I'm going to close this now, but will continue to address the issue via #4, where I've already pinged you. Thanks for finally giving me the incentive to pursue that!

**Comment by mpadge** [comment]
@pawelru I've implemented tree-sitter parsing of external calls in #62, which currently gives these results for your package:

``` r
path <- "/<local>/<path>/<to>/teal"
has_tabs <- FALSE
pkg_name <- basename (path)

# The current pkgstats approach with 'ctags':
tags_r <- withr::with_dir (path, get_ctags ("R", has_tabs))
ex <- pkgstats:::external_call_network (tags_r, path, pkg_name)
ex <- ex [which (!ex$package == "base"), ]
nrow (ex)
#> [1] 495

# New tree-sitter parsing from code in #62:
tags_treesitter <- get_treesitter_tags (path)
ex <- pkgstats:::external_call_network (tags_treesitter, path, pkg_name)
ex <- ex [which (!ex$package == "base"), ]
nrow (ex)
#> [1] 395

ex <- data.frame (checkglobals::check_pkg (path))
ex <- ex [which (!ex$package == "base"), ]
nrow (ex)
#> [1] 159
```

<sup>Created on 2024-09-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

That suggests current approach here is actually okay. The tree-sitter values may be presumed to provide a "true" reference. I'll investigate further over in #62

**Comment by pawelru** [comment]
Thank you for follow ups on this and apologies for a delayed answer. I was on a short break and right afterwards had to focus on something different. Now I am back into this and it looking very very promising. Thanks again. 
Even though the totals are somewhat similar I actually have found some differences. Please find below some top picks. For each of these, I have found treesitter to be closer to the truth.

Please find below a few examples that I was able to check quickly. I'm using the updated local copy of a referenced repo so the overall numbers might be slightly different to yours but the difference is rather minimal (e.g. I have 511 and you got 495). I'm yet to check it against checkglobals.
This was my starting point - to check the top picks
```
r$> ex_r |> group_by(package, call) |> summarise(N = n()) |> arrange(-N)
`summarise()` has grouped output by 'package'. You can override using the `.groups` argument.
# A tibble: 269 × 3
# Groups:   package [22]
   package call        N
   <chr>   <chr>   <int>
 1 base    list       69
 2 base    c          67
 3 utils   data       56
 4 teal    modules    51
 5 base    lapply     36
 6 base    names      27
 7 base    args       25
 8 base    sprintf    21
 9 base    class      20
10 base    if         20
# ℹ 259 more rows
# ℹ Use `print(n = ...)` to see more rows
```
```
r$> ex_t |> group_by(package, call) |> summarise(N = n()) |> arrange(-N)
`summarise()` has grouped output by 'package'. You can override using the `.groups` argument.
# A tibble: 343 × 3
# Groups:   package [26]
   package call          N
   <chr>   <chr>     <int>
 1 base    c           103
 2 base    sprintf      73
 3 base    length       63
 4 base    list         62
 5 logger  log_debug    57
 6 base    names        55
 7 base    inherits     48
 8 base    lapply       47
 9 base    is.null      41
10 base    attr         36
# ℹ 333 more rows
# ℹ Use `print(n = ...)` to see more rows
```

- interestingly, `base::list()` got a very similar results - 69 vs 62. I skipped the analysis of this.

- `foo <- function(data, ...) {...}` or `bar(data = data, ...)` - ctags recognises this as a `utils::data`
  - there are a lot of functions with `data` arguments
  ```
  r$> ex_r |> filter(package == "utils" & call == "data") |> nrow()
  [1] 56
  r$> ex_t |> filter(package == "utils" & call == "data") |> nrow()
  [1] 6
  ```
  - there are lot of functions with `modules` arguments. This one is a even more tricky because there is an exported `modules()` function.
  ```
  r$> ex_r |> filter(package == "teal" & call == "modules") |> nrow()
  [1] 51
  r$> ex_t |> filter(package == "teal" & call == "modules") |> nrow()
  [1] 0
  ```

- (now I'm guessing the pattern) `if(length(x) > 0)` - ctags does not recognise `base::length`
  ```
  r$> ex_r |> filter(package == "base" & call == "length") |> nrow()
  [1] 7
  r$> ex_t |> filter(package == "base" & call == "length") |> nrow()
  [1] 63
  ```

- here I'm out of ides why:
  ```
  r$> ex_r |> filter(package == "logger" & call == "log_debug") |> nrow()
  [1] 0
  r$> ex_t |> filter(package == "logger" & call == "log_debug") |> nrow()
  [1] 57
  ```
  https://github.com/search?q=repo%3Ainsightsengineering%2Fteal%20logger%3A%3Alog_debug&type=code

- `lapply(filter, function(x) {...})` - ctags recognises this as a `stats::filter`
  ```
  r$> ex_r |> filter(package == "stats" & call == "filter") |> nrow()
  [1] 16
  r$> ex_t |> filter(package == "stats" & call == "filter") |> nrow()
  [1] 0
  ```

These are just top diffs that I checked. Even though the sum is comparable - there are actually some differences - both positive and negative. Now I don't want you to go into the details - that's not the point of my message. What I just wanted to say here is that based on that brief analysis, the treesitter approach looks very very promising!

**Comment by mpadge** [comment]
Thanks @pawelru for pursuing this further. I've implemented a full treesitter function tagger in [currently experiment package, `pkgsimil`](https://github.com/ropensci-review-tools/pkgsimil) (in even more efficient form). You just need to install that package, and run:
``` r
pkgsimil::pkgsimil_tag_fns(path)
```

Just note that things are likely to change quickly in that package, including function names and potentially name of package. But the underlying algorithm works really well, and identifies every single function call. 

That will eventually find it's way over here, but doing so will require rebuilding our entire [CRAN database](https://github.com/ropensci-review-tools/pkgstats/releases/tag/v0.1.6) to update function call data. So that will have to wait a while ...
